Control to start the master

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,54 +1,65 @@
 #!/bin/bash
 
-pid=pid/puppet.pid
-name="puppet"
+# Set envionment
+source ${OPENSHIFT_CARTRIDGE_SDK_BASH}
+export PUPPET_DIR=${OPENSHIFT_PUPPET_DIR}
+export PATH=${PUPPET_DIR}/bin/puppet/bin:${PUPPET_DIR}/bin/facter/bin:${PATH}
+export RUBYLIB=${PUPPET_DIR}/bin//puppet/lib
 
-function status() {
-    client_result $pwd
-    if [ -f $pid ] && ( kill -0 $(cat $pid) ); then
-        client_result "$name is running"
-    fi
-}
+pid=${PUPPET_DIR}/var/run/puppet.pid
+name="puppet master"
 
-function update() {
-    stop
-    ./.openshift/action_hooks/build
-}
-
-function start() {
-    if ! [ -f $pid ]
+status() {
+    client_result ${pwd}
+    if [ -f ${pid} ] && ( kill -0 $(< ${pid}) )
     then
-        echo "Starting puppet"
-        ret=$?
-        if [ $ret -ne 0 ]
-	then
-            echo "$name failed to start - $ret" 1>&2
-            return $ret
-        fi
+        client_result "${name} is running"
     fi
 }
 
-function stop() {
+start() {
+    if [[ ! -f ${pid} ]]
+    then
+        echo "Starting puppet master"
+	puppet master --config ./temporary_config.conf
+        rc=${?}
+        p-${!}
+        if [[ ${rc} -ne 0 ]]
+	then
+            echo "${name} failed to start - ${rc}" 1>&2
+            return ${rc}
+        fi
+        echo ${p} > ${pid}
+    fi
+}
+
+stop() {
+    if [[ -f ${pid} ]]
+    then
+    	kill $(<${pid})
+    fi
+    rm -f ${pid}
     return 0
 }
 
-function restart() {
-    stop; start
+restart() {
+    stop
+    start
 }
 
-function build() {
+build() {
     echo
 }
 
-function post-deploy() {
+post-deploy() {
     echo
 }
 
-function pre-build() {
+pre-build() {
     echo
 }
 
-function tidy() {
+tidy() {
     echo
 }
 
@@ -57,24 +68,22 @@ function tidy() {
 #
 
 # Ensure arguments.
-if ! [ $# -gt 0 ]; then
-    echo "Usage: $0 [start|restart|graceful|graceful-stop|stop|status|update|use-source]"
+if [[ $# -eq 0 ]]
+then
+    echo "Usage: ${0} [start|restart|stop|status]"
     exit 1
 fi
 
-# Source utility functions.
-source $OPENSHIFT_CARTRIDGE_SDK_BASH
-
 # Handle commands.
-case "$1" in
-    start)               start       ;;
-    restart|graceful)    restart     ;;
-    graceful-stop|stop)  stop        ;;
-    status)              status      ;;
-    build)               build       ;;
-    pre-build)           pre-build   ;;
-    post-deploy)         post-deploy ;;
-    tidy)                tidy        ;;
-    update)              update      ;;
+case "${1}" in
+    start)	start       ;;
+    restart)	restart     ;;
+    stop)	stop        ;;
+    status)	status      ;;
     *)
+	echo "Usage: ${0} [start|restart|stop|status]"
+	exit 1
+	;;
 esac
+
+exit 0
